name: Preprocess CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v4

      # Setup Python 3.12.7
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn joblib

      # Step 4: Jalankan script Python untuk preprocessing
      - name: Run preprocessing script
        run: python preprocess.py

      # Step 5: Simpan file hasil preprocessing ke artifact
      - name: Upload processed CSV as artifact
        uses: actions/upload-artifact@v4
        with:
          name: diabetes-preprocessed
          path: preprocessing/diabetes_preprocessing.csv
